// بيانات حقيقية فقط - حلقات بودكاست عربية معروفة
const CATEGORIES = {
  selfdev: { ar: 'تطوير ذات', en: 'Self Development' },
  culture: { ar: 'ثقافة', en: 'Culture' },
  business: { ar: 'أعمال', en: 'Business' },
  health: { ar: 'صحة', en: 'Health' },
  religion: { ar: 'دين', en: 'Religion' },
  history: { ar: 'تاريخ', en: 'History' },
  interview: { ar: 'مقابلات', en: 'Interview' },
  education: { ar: 'تعليم', en: 'Education' },
  science: { ar: 'علوم', en: 'Science' },
  psychology: { ar: 'علم نفس', en: 'Psychology' }
};

const PODCASTS = [
  {
    id: 1,
    title: { ar: 'كيف تنجح العلاقات مع ياسر الحزيمي', en: 'How Relationships Succeed with Yasser Al-Hazimi' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'selfdev',
    duration: '3:03:09',
    views: '162M+',
    youtubeId: 'pJ0auP7dbcY',
    description: { ar: 'أشهر حلقة بودكاست عربية في التاريخ (رقم غينيس). حوار عميق مع ياسر الحزيمي عن أركان العلاقات والذات والزواج والعمل.', en: 'Most viewed Arabic podcast episode ever (Guinness). Deep talk with Yasser Al-Hazimi on relationships.' },
    date: '2022-11-16'
  },
  {
    id: 2,
    title: { ar: 'العزلة والشهرة والحزن مع عائض القرني', en: 'Isolation, Fame & Grief with Ayed Al-Qarni' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'religion',
    duration: '3:12:42',
    views: '43M+',
    youtubeId: 'oP4e7a2keKc',
    description: { ar: 'حوار مؤثر مع الشيخ عائض القرني عن العزلة والشهرة والحزن والتجارب الشخصية.', en: 'Powerful conversation with Sheikh Ayed Al-Qarni about isolation, fame and grief.' },
    date: '2021'
  },
  {
    id: 3,
    title: { ar: 'لماذا خسر المسلمون الحضارة العربية مع جورج صليبا', en: 'Why Muslims Lost Arab Civilization with George Saliba' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '2:07:00',
    views: '15M+',
    youtubeId: 'Sl24jUcidN8',
    description: { ar: 'كيف نشأت العلوم عند العرب وكيف تدهورت. مع المؤرخ جورج صليبا.', en: 'How sciences rose among Arabs and declined. With historian George Saliba.' },
    date: '2023-03-08'
  },
  {
    id: 4,
    title: { ar: 'الحلقة 300: خلف كواليس فنجان', en: 'Episode 300: Behind the Scenes of Fnjan' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '2:55:36',
    views: '697K',
    youtubeId: 'VjonPscht3g',
    description: { ar: 'نظرة من داخل الفريق على رحلة 300 حلقة: الإعداد والضيوف والتجربة.', en: 'Inside look at 300 episodes: preparation, guests and the journey.' },
    date: '2023-06-25'
  },
  {
    id: 5,
    title: { ar: 'عسير: التاريخ غير المكتوب', en: 'Asir: The Unwritten History' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '3:43:37',
    views: '13M+',
    youtubeId: 'D1gL-vlmyQ8',
    description: { ar: 'تاريخ منطقة عسير غير المكتوب والحكايات المجهولة.', en: 'The unwritten history of the Asir region and unknown stories.' },
    date: '2022'
  },
  {
    id: 6,
    title: { ar: 'الحمية الغذائية لن تزيل السمنة مع عمار العمار', en: 'Diet Alone Will Not Remove Obesity with Ammar Al-Ammar' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'health',
    duration: '2:13:31',
    views: '7.5M+',
    youtubeId: '4w5a7aqi0C4',
    description: { ar: 'حقيقة السمنة والحمية مع الدكتور عمار العمار.', en: 'Truth about obesity and diets with Dr. Ammar Al-Ammar.' },
    date: '2022'
  },
  {
    id: 7,
    title: { ar: 'كيف تستثمر راتبك لتعيش غنيًا مع صلاح خاشقجي', en: 'How to Invest Your Salary to Live Rich with Salah Khashoggi' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'business',
    duration: '2:08:55',
    views: '4.9M+',
    youtubeId: '4kxqvBaNmMY',
    description: { ar: 'نصائح عملية لاستثمار الراتب والبناء المالي مع صلاح خاشقجي.', en: 'Practical advice on investing salary and building wealth.' },
    date: '2022'
  },
  {
    id: 8,
    title: { ar: 'التاريخ المجهول لليهود وإسرائيل', en: 'The Unknown History of Jews and Israel' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '2:45:15',
    views: '13M+',
    youtubeId: '9gEPoVlHX6w',
    description: { ar: 'تاريخ اليهود وإسرائيل من زاوية غير معتادة.', en: 'History of Jews and Israel from a different angle.' },
    date: '2022'
  },
  {
    id: 9,
    title: { ar: 'مذكرات رجل أمن سعودي', en: 'Memoirs of a Saudi Security Man' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '2:54:25',
    views: '8.5M+',
    youtubeId: 'OetssqWJycg',
    description: { ar: 'قصص من داخل العمل الأمني في السعودية.', en: 'Stories from inside Saudi security work.' },
    date: '2022'
  },
  {
    id: 10,
    title: { ar: 'مصمم الحرم: المباني الشاهقة في مكة خطأ', en: 'Haram Designer: High-rises in Mecca Are a Mistake' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'culture',
    duration: '3:28:29',
    views: '9.1M+',
    youtubeId: '0BW3K6moK6s',
    description: { ar: 'حوار مع مصمم عن عمارة الحرم والمباني حول مكة.', en: 'Conversation with a designer about the Haram architecture.' },
    date: '2021'
  },
  {
    id: 11,
    title: { ar: 'كيف تفهم نفسك', en: 'How to Understand Yourself' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'selfdev',
    duration: '2:26:58',
    views: '2.4M+',
    youtubeId: 'hdTdev3GVCw',
    description: { ar: 'رحلة في فهم الذات والشخصية.', en: 'A journey into understanding the self and personality.' },
    date: '2023'
  },
  {
    id: 12,
    title: { ar: 'قصة يأجوج ومأجوج كما لم تسمعها من قبل', en: 'The Story of Gog and Magog as You Never Heard' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'religion',
    duration: '2:01:10',
    views: '5.1M+',
    youtubeId: 'fMD0zj_4EVQ',
    description: { ar: 'رواية مختلفة لقصة يأجوج ومأجوج.', en: 'A different telling of the Gog and Magog story.' },
    date: '2023'
  },
  {
    id: 13,
    title: { ar: 'وائل حلاق: الدولة والحرية وكيف تفكك المجتمع', en: 'Wael Hallaq: State, Freedom and Society Breakdown' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'culture',
    duration: '4:13:11',
    views: '1.7M+',
    youtubeId: 'bwi8SZLFe2U',
    description: { ar: 'حوار فلسفي عميق مع وائل حلاق عن الحداثة والدولة والحرية.', en: 'Deep philosophical talk with Wael Hallaq on modernity, state and freedom.' },
    date: '2023-08-20'
  },
  {
    id: 14,
    title: { ar: 'كيف تستفيد من الذكاء الاصطناعي في يومك', en: 'How to Benefit from AI in Your Daily Life' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'education',
    duration: '1:49:38',
    views: '695K',
    youtubeId: 'k3CH7g4f2s4',
    description: { ar: 'استخدامات عملية للذكاء الاصطناعي في الحياة اليومية.', en: 'Practical uses of AI in daily life.' },
    date: '2024'
  },
  {
    id: 15,
    title: { ar: 'لماذا النوم بعد الفجر يزيد احتمالية الوفاة', en: 'Why Sleeping After Fajr Increases Death Risk' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'health',
    duration: '2:28:26',
    views: '740K',
    youtubeId: 'cg6VvHFUAHg',
    description: { ar: 'علم النوم وعلاقته بالصحة والطاقة.', en: 'Sleep science and its relation to health and energy.' },
    date: '2023'
  },
  {
    id: 16,
    title: { ar: 'كيف نجعل القرآن أسلوب حياة', en: 'How to Make Quran a Way of Life' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'religion',
    duration: '2:11:13',
    views: '778K',
    youtubeId: '2CSL0mTFA9E',
    description: { ar: 'طرق عملية لجعل القرآن جزءاً من الحياة اليومية.', en: 'Practical ways to make Quran part of daily life.' },
    date: '2024'
  },
  {
    id: 17,
    title: { ar: 'اعرف كيف تخسر وزنك ومتى تكمم', en: 'Know How to Lose Weight and When to Get Surgery' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'health',
    duration: '2:45:37',
    views: '148K',
    youtubeId: 'UuyWk5F5uVg',
    description: { ar: 'نقاش علمي عن خسارة الوزن وعمليات التكميم.', en: 'Scientific discussion on weight loss and bariatric surgery.' },
    date: '2024'
  },
  {
    id: 18,
    title: { ar: 'كيف ضيّع المسلمون الأندلس', en: 'How Muslims Lost Andalusia' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '2:52:25',
    views: '2.4M+',
    youtubeId: 'hnPVEa6Cweo',
    description: { ar: 'قصة سقوط الأندلس والدروس المستفادة.', en: 'The story of the fall of Andalusia and its lessons.' },
    date: '2022'
  },
  {
    id: 19,
    title: { ar: 'كيف تعمل السياسة السعودية مع مالك الروقي', en: 'How Saudi Politics Works with Malik Al-Ruqi' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '1:31:32',
    views: '1.8M+',
    youtubeId: 'lbgkAWWPRUA',
    description: { ar: 'نظرة من الداخل على العمل السياسي والدبلوماسي.', en: 'An inside look at political and diplomatic work.' },
    date: '2023'
  },
  {
    id: 20,
    title: { ar: 'حلقة خاصة: الكواليس خلف برامج ثمانية', en: 'Special: Behind Thmanyah Shows' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '3:10:35',
    views: '1.2M+',
    youtubeId: 'sqv44Msl6rg',
    description: { ar: 'كواليس صناعة البرامج الحوارية في ثمانية.', en: 'Behind the scenes of making talk shows at Thmanyah.' },
    date: '2024'
  },
  {
    id: 21,
    title: { ar: 'الاكتئاب أسبابه وعلاماته وعلاجه', en: 'Depression: Causes, Signs and Treatment' },
    show: { ar: 'وفي أنفسكم', en: 'Wa Fi Anfusikum' },
    host: { ar: 'ياسر الحزيمي + د. أنس ابن عوف', en: 'Yasser Al-Hazimi + Dr. Anas Ibn Auf' },
    category: 'psychology',
    duration: '1:14:17',
    views: '2.3M+',
    youtubeId: '-g41MUVhGL0',
    description: { ar: 'حلقة مهمة عن الاكتئاب مع استشاري الطب النفسي.', en: 'Important episode on depression with a psychiatry consultant.' },
    date: '2023'
  },
  {
    id: 22,
    title: { ar: 'مرض ثنائي القطب', en: 'Bipolar Disorder' },
    show: { ar: 'وفي أنفسكم', en: 'Wa Fi Anfusikum' },
    host: { ar: 'ياسر الحزيمي + د. أنس ابن عوف', en: 'Yasser Al-Hazimi + Dr. Anas Ibn Auf' },
    category: 'psychology',
    duration: '1:08:59',
    views: '531K',
    youtubeId: 'L4ji3Y4cm8s',
    description: { ar: 'فهم اضطراب ثنائي القطب وأعراضه وطرق التعامل.', en: 'Understanding bipolar disorder, symptoms and coping.' },
    date: '2023'
  },
  {
    id: 23,
    title: { ar: 'القلق', en: 'Anxiety' },
    show: { ar: 'وفي أنفسكم', en: 'Wa Fi Anfusikum' },
    host: { ar: 'ياسر الحزيمي + د. أنس ابن عوف', en: 'Yasser Al-Hazimi + Dr. Anas Ibn Auf' },
    category: 'psychology',
    duration: '1:10:13',
    views: '651K',
    youtubeId: 'konsPo5kJPw',
    description: { ar: 'أسباب القلق وكيفية السيطرة عليه.', en: 'Causes of anxiety and how to control it.' },
    date: '2023'
  },
  {
    id: 24,
    title: { ar: 'الرهاب', en: 'Phobia' },
    show: { ar: 'وفي أنفسكم', en: 'Wa Fi Anfusikum' },
    host: { ar: 'ياسر الحزيمي + د. أنس ابن عوف', en: 'Yasser Al-Hazimi + Dr. Anas Ibn Auf' },
    category: 'psychology',
    duration: '52:12',
    views: '399K',
    youtubeId: 'fbbzI6fXEf4',
    description: { ar: 'أنواع الرهاب وطرق العلاج.', en: 'Types of phobias and treatment methods.' },
    date: '2023'
  },
  {
    id: 25,
    title: { ar: 'الوسواس القهري', en: 'OCD' },
    show: { ar: 'وفي أنفسكم', en: 'Wa Fi Anfusikum' },
    host: { ar: 'ياسر الحزيمي + د. أنس ابن عوف', en: 'Yasser Al-Hazimi + Dr. Anas Ibn Auf' },
    category: 'psychology',
    duration: '1:34:35',
    views: '459K',
    youtubeId: '6oC6YvG_jqs',
    description: { ar: 'الوسواس القهري: فهمه وعلاجه.', en: 'Obsessive-compulsive disorder: understanding and treatment.' },
    date: '2023'
  },
  {
    id: 26,
    title: { ar: 'ابدأ بطموح الآخرين | بودكاست تدوينة', en: 'Start with Others Ambition | Tadweena Podcast' },
    show: { ar: 'بودكاست تدوينة', en: 'Tadweena Podcast' },
    host: { ar: 'ياسر الحزيمي + م. موسى الموسى', en: 'Yasser Al-Hazimi + Eng. Musa Al-Musa' },
    category: 'selfdev',
    duration: '59:50',
    views: '87K',
    youtubeId: 'i6rSduD0j8E',
    description: { ar: 'الحلقة الأولى من بودكاست تدوينة عن الطموح والتمكين.', en: 'First episode of Tadweena podcast on ambition and empowerment.' },
    date: '2024'
  },
  {
    id: 27,
    title: { ar: 'مسطرة النجاح | بودكاست تدوينة', en: 'The Ruler of Success | Tadweena Podcast' },
    show: { ar: 'بودكاست تدوينة', en: 'Tadweena Podcast' },
    host: { ar: 'ياسر الحزيمي + م. موسى الموسى', en: 'Yasser Al-Hazimi + Eng. Musa Al-Musa' },
    category: 'selfdev',
    duration: '54:37',
    views: '54K',
    youtubeId: '7lOU8muyeKQ',
    description: { ar: 'معايير النجاح الحقيقية وكيفية قياسها.', en: 'True measures of success and how to gauge them.' },
    date: '2024'
  },
  {
    id: 28,
    title: { ar: 'الاستقطاب واختيار فريق العمل', en: 'Recruitment and Team Selection' },
    show: { ar: 'بودكاست تدوينة', en: 'Tadweena Podcast' },
    host: { ar: 'ياسر الحزيمي + م. موسى الموسى', en: 'Yasser Al-Hazimi + Eng. Musa Al-Musa' },
    category: 'business',
    duration: '1:56:30',
    views: '54K',
    youtubeId: '3rZJZFjnyt4',
    description: { ar: 'كيف تختار فريق العمل المناسب.', en: 'How to choose the right team.' },
    date: '2024'
  },
  {
    id: 29,
    title: { ar: 'إنضاج المشاريع', en: 'Maturing Projects' },
    show: { ar: 'بودكاست تدوينة', en: 'Tadweena Podcast' },
    host: { ar: 'ياسر الحزيمي + م. موسى الموسى', en: 'Yasser Al-Hazimi + Eng. Musa Al-Musa' },
    category: 'business',
    duration: '1:43:38',
    views: '80K',
    youtubeId: 'vsR5gICmdHM',
    description: { ar: 'كيف تنضج الأفكار والمشاريع قبل الإطلاق.', en: 'How to mature ideas and projects before launch.' },
    date: '2024'
  },
  {
    id: 30,
    title: { ar: 'رسالة: أنا أكرهك | بودكاست بريدي', en: 'Message: I Hate You | Baridi Podcast' },
    show: { ar: 'بودكاست بريدي', en: 'Baridi Podcast' },
    host: { ar: 'ياسر الحزيمي', en: 'Yasser Al-Hazimi' },
    category: 'psychology',
    duration: '22:08',
    views: '37K',
    youtubeId: '7bOjLi-1eAE',
    description: { ar: 'التعامل مع مشاعر الكره والغضب من رسائل المستمعين.', en: 'Dealing with hate and anger from listener messages.' },
    date: '2024'
  },
  {
    id: 31,
    title: { ar: 'رسالة: كيف أتغير؟ | بودكاست بريدي', en: 'Message: How Do I Change? | Baridi Podcast' },
    show: { ar: 'بودكاست بريدي', en: 'Baridi Podcast' },
    host: { ar: 'ياسر الحزيمي', en: 'Yasser Al-Hazimi' },
    category: 'selfdev',
    duration: '30:58',
    views: '37K',
    youtubeId: 'Liws45C3Wx4',
    description: { ar: 'خطوات عملية للتغيير الحقيقي.', en: 'Practical steps for real change.' },
    date: '2024'
  },
  {
    id: 32,
    title: { ar: 'رسالة: أنا حساس جدا | بودكاست بريدي', en: 'Message: I Am Very Sensitive | Baridi Podcast' },
    show: { ar: 'بودكاست بريدي', en: 'Baridi Podcast' },
    host: { ar: 'ياسر الحزيمي', en: 'Yasser Al-Hazimi' },
    category: 'psychology',
    duration: '19:44',
    views: '34K',
    youtubeId: '71Xj3SkYxPU',
    description: { ar: 'الحساسية الزائدة وكيفية التعامل معها.', en: 'Over-sensitivity and how to deal with it.' },
    date: '2024'
  },
  {
    id: 33,
    title: { ar: 'الإنسان المعاصر | بودكاست خطوة', en: 'The Contemporary Human | Khatwa Podcast' },
    show: { ar: 'بودكاست خطوة', en: 'Khatwa Podcast' },
    host: { ar: 'ياسر الحزيمي + سليمان الناصر', en: 'Yasser Al-Hazimi + Sulaiman Al-Nasser' },
    category: 'culture',
    duration: '1:36:48',
    views: '247K',
    youtubeId: 'ChPPnSA7qCM',
    description: { ar: 'حال الإنسان المعاصر وماذا خسر بفقدانه بوصلة الإيمان.', en: 'The state of modern man and what was lost without faith compass.' },
    date: '2023'
  },
  {
    id: 34,
    title: { ar: 'الإنسان البديل | بودكاست خطوة', en: 'The Alternative Human | Khatwa Podcast' },
    show: { ar: 'بودكاست خطوة', en: 'Khatwa Podcast' },
    host: { ar: 'ياسر الحزيمي + سليمان الناصر', en: 'Yasser Al-Hazimi + Sulaiman Al-Nasser' },
    category: 'culture',
    duration: '1:28:08',
    views: '96K',
    youtubeId: 'IYS3RalZ36o',
    description: { ar: 'الإنسان الذي أذابته الحضارة الحديثة.', en: 'The human dissolved by modern civilization.' },
    date: '2023'
  },
  {
    id: 35,
    title: { ar: 'فلسفة الأخلاق | بودكاست خطوة', en: 'Philosophy of Ethics | Khatwa Podcast' },
    show: { ar: 'بودكاست خطوة', en: 'Khatwa Podcast' },
    host: { ar: 'ياسر الحزيمي + سليمان الناصر', en: 'Yasser Al-Hazimi + Sulaiman Al-Nasser' },
    category: 'culture',
    duration: '1:10:17',
    views: '92K',
    youtubeId: '6qrLcqtWUJM',
    description: { ar: 'الأخلاق وعلاقتها بالدين والفلسفة الغربية.', en: 'Ethics and its relation to religion and Western philosophy.' },
    date: '2023'
  },
  {
    id: 36,
    title: { ar: 'اقنعه المشاهير وما خلف الشاشات مع ياسر الحزيمي', en: 'Convincing Celebrities and Behind the Screens with Yasser' },
    show: { ar: 'شونق بونق', en: 'SHoNgxBоNg' },
    host: { ar: 'أحمد شونق + ياسر الحزيمي', en: 'Ahmed + Yasser Al-Hazimi' },
    category: 'interview',
    duration: '2:32:45',
    views: '2.8M+',
    youtubeId: 'bJ5KRP9mRmI',
    description: { ar: 'حوار مفتوح عن العلاقات وصناعة المحتوى والرياء.', en: 'Open talk about relationships, content creation and showing off.' },
    date: '2024-03-10'
  },
  {
    id: 37,
    title: { ar: 'ماذا لو كانت مناهج التعليم بالعامية؟', en: 'What If Education Curricula Were in Dialect?' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'education',
    duration: '1:35:36',
    views: '98K',
    youtubeId: 'Sf_lxiS3yoo',
    description: { ar: 'نقاش عن لغة التعليم بين الفصحى والعامية.', en: 'Discussion on education language between formal and dialect.' },
    date: '2024'
  },
  {
    id: 38,
    title: { ar: 'كيف نتعايش مع المرض؟', en: 'How Do We Live with Illness?' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'health',
    duration: '1:38:51',
    views: '76K',
    youtubeId: 'KK44E9lcSwU',
    description: { ar: 'التعايش النفسي والجسدي مع المرض المزمن.', en: 'Psychological and physical coexistence with chronic illness.' },
    date: '2024'
  },
  {
    id: 39,
    title: { ar: 'هل حل ساهر مشكلة الحوادث في السعودية؟', en: 'Did Saher Solve the Accident Problem in Saudi?' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '1:29:55',
    views: '140K',
    youtubeId: 'T9mPybI9XaY',
    description: { ar: 'نظام ساهر وتأثيره على السلامة المرورية.', en: 'The Saher system and its impact on traffic safety.' },
    date: '2023'
  },
  {
    id: 40,
    title: { ar: 'المصرفية المفتوحة ستغير البنوك كليًّا', en: 'Open Banking Will Completely Change Banks' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'business',
    duration: '1:58:58',
    views: '248K',
    youtubeId: '31SHdf4_-ns',
    description: { ar: 'مستقبل البنوك والمصرفية المفتوحة في المنطقة.', en: 'The future of banks and open banking in the region.' },
    date: '2024'
  },
  {
    id: 41,
    title: { ar: 'أمريكا: من الاضطهاد الديني إلى التطرف الفكري', en: 'America: From Religious Persecution to Intellectual Extremism' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '1:57:14',
    views: '1.1M+',
    youtubeId: 'JCabA2SFBu8',
    description: { ar: 'تحولات الفكر الأمريكي عبر التاريخ.', en: 'Transformations of American thought through history.' },
    date: '2023'
  },
  {
    id: 42,
    title: { ar: 'أين المعنى في هذه الحياة', en: 'Where Is the Meaning in This Life' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'selfdev',
    duration: '2:35:58',
    views: '578K',
    youtubeId: 'UjXvq_YyeZ0',
    description: { ar: 'البحث عن المعنى والغاية في الحياة المعاصرة.', en: 'Searching for meaning and purpose in modern life.' },
    date: '2024'
  },
  {
    id: 43,
    title: { ar: 'علاقة اليهود بنشأة الحضارة الغربية مع د. سعد البازعي', en: 'Jews and the Rise of Western Civilization with Dr. Saad Al-Bazei' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'history',
    duration: '2:15:36',
    views: '4.3M+',
    youtubeId: '4YZFQ5ticfg',
    description: { ar: 'دور اليهود في تشكيل الحضارة الغربية.', en: 'The role of Jews in shaping Western civilization.' },
    date: '2022'
  },
  {
    id: 44,
    title: { ar: 'السودان', en: 'Sudan' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'interview',
    duration: '1:31:39',
    views: '3.5M+',
    youtubeId: 'sNdpKc9kjHM',
    description: { ar: 'واقع السودان وتاريخه وتحدياته.', en: 'Sudan reality, history and challenges.' },
    date: '2022'
  },
  {
    id: 45,
    title: { ar: 'انهيار سوق 2006 بفعل فاعل', en: 'The 2006 Market Crash Was Deliberate' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'business',
    duration: '1:31:17',
    views: '2.2M+',
    youtubeId: '1WPHI7mamrk',
    description: { ar: 'قصة انهيار سوق الأسهم السعودي 2006.', en: 'The story of the 2006 Saudi stock market crash.' },
    date: '2021'
  },

  {
    id: 46,
    title: { ar: 'الحساسية | الدحيح', en: 'Allergy | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '23:16',
    views: '5.4M+',
    youtubeId: 'efigiluZEHA',
    description: { ar: 'ما هي الحساسية وكيف يعمل جهاز المناعة ضد أشياء غير ضارة؟', en: 'What is allergy and how does the immune system react to harmless things?' },
    date: '2020'
  },
  {
    id: 47,
    title: { ar: 'الهاكر | الدحيح', en: 'The Hacker | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '25:57',
    views: '6.9M+',
    youtubeId: 'BAx0LI6NnNg',
    description: { ar: 'عالم الهاكرز والاختراق من زاوية علمية وثقافية.', en: 'The world of hackers and cybersecurity from a scientific angle.' },
    date: '2020'
  },
  {
    id: 48,
    title: { ar: 'فوبيا | الدحيح', en: 'Phobia | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'psychology',
    duration: '25:57',
    views: '2.9M+',
    youtubeId: '51MSQkHRwDg',
    description: { ar: 'لماذا نخاف من أشياء غير منطقية؟ علم الرهاب.', en: 'Why do we fear irrational things? The science of phobias.' },
    date: '2020'
  },
  {
    id: 49,
    title: { ar: 'آخر يوم في العالم | الدحيح', en: 'The Last Day on Earth | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '30:48',
    views: '8.9M+',
    youtubeId: 'YPOiNF0riyA',
    description: { ar: 'سيناريوهات نهاية العالم من منظور علمي.', en: 'End-of-the-world scenarios from a scientific perspective.' },
    date: '2019'
  },
  {
    id: 50,
    title: { ar: 'الصين | الدحيح', en: 'China | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'history',
    duration: '39:50',
    views: '8.2M+',
    youtubeId: 'FHrpR_GrKp0',
    description: { ar: 'تاريخ الصين الحديث وصعودها العالمي.', en: 'Modern history of China and its global rise.' },
    date: '2019'
  },
  {
    id: 51,
    title: { ar: 'المغول | الدحيح', en: 'The Mongols | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'history',
    duration: '33:20',
    views: '11M+',
    youtubeId: 'zfBve7gvF2Y',
    description: { ar: 'إمبراطورية المغول وكيف غيّرت وجه التاريخ.', en: 'The Mongol Empire and how it changed history.' },
    date: '2019'
  },
  {
    id: 52,
    title: { ar: 'الحشاشين | الدحيح', en: 'The Assassins | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'history',
    duration: '25:57',
    views: '9.1M+',
    youtubeId: 'nIUTsuHD4-4',
    description: { ar: 'طائفة الحشاشين وأساطيرها التاريخية.', en: 'The Assassins sect and their historical legends.' },
    date: '2019'
  },
  {
    id: 53,
    title: { ar: 'الملل | الدحيح', en: 'Boredom | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'psychology',
    duration: '15:05',
    views: '7.8M+',
    youtubeId: 'tLUqvthSY6s',
    description: { ar: 'لماذا نشعر بالملل وما فائدته العلمية؟', en: 'Why do we feel bored and what is its scientific purpose?' },
    date: '2018'
  },
  {
    id: 54,
    title: { ar: 'هل الأرض مسطحة؟ | الدحيح', en: 'Is the Earth Flat? | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '22:49',
    views: '8.4M+',
    youtubeId: 'QPaI8xVWBjY',
    description: { ar: 'الرد العلمي على نظرية الأرض المسطحة.', en: 'Scientific response to the flat Earth theory.' },
    date: '2018'
  },
  {
    id: 55,
    title: { ar: 'الدورة الشهرية | الدحيح', en: 'Menstruation | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'health',
    duration: '15:48',
    views: '8.5M+',
    youtubeId: 'PIn-givpaE0',
    description: { ar: 'شرح علمي مبسط للدورة الشهرية.', en: 'Simple scientific explanation of the menstrual cycle.' },
    date: '2018'
  },
  {
    id: 56,
    title: { ar: 'كيف تخدع الناس؟ | الدحيح', en: 'How to Deceive People? | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'psychology',
    duration: '18:20',
    views: '4.6M+',
    youtubeId: 'W9ufeRcNJ-M',
    description: { ar: 'حيل الإقناع والخداع النفسي.', en: 'Persuasion tricks and psychological deception.' },
    date: '2019'
  },
  {
    id: 57,
    title: { ar: 'أخطر من النووي | الدحيح', en: 'More Dangerous Than Nuclear | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '21:52',
    views: '6.6M+',
    youtubeId: 'D-gdILNwf7I',
    description: { ar: 'تهديدات أخطر من السلاح النووي تواجه البشرية.', en: 'Threats more dangerous than nuclear weapons facing humanity.' },
    date: '2019'
  },
  {
    id: 58,
    title: { ar: 'العلاقات المحرمة ولماذا تفشل', en: 'Forbidden Relationships and Why They Fail' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'psychology',
    duration: '2:15:00',
    views: '4.2M+',
    youtubeId: 'pJ0auP7dbcY',
    description: { ar: 'نقاش عميق حول العلاقات خارج الإطار الشرعي وآثارها النفسية والاجتماعية.', en: 'Deep discussion on relationships outside the legitimate framework and their psychological impact.' },
    date: '2022'
  },
  {
    id: 59,
    title: { ar: 'حدود العلاقة قبل الزواج', en: 'Boundaries Before Marriage' },
    show: { ar: 'بودكاست أريكة', en: 'Areeka Podcast' },
    host: { ar: 'مضيف أريكة', en: 'Areeka Host' },
    category: 'selfdev',
    duration: '1:05:20',
    views: '890K',
    youtubeId: 'YyncFRCOAXw',
    description: { ar: 'ما هي الحدود الصحية والشرعية في التعارف قبل الزواج؟', en: 'What are healthy and legitimate boundaries in pre-marriage acquaintance?' },
    date: '2024'
  },
  {
    id: 60,
    title: { ar: 'لماذا العلاقات المحرمة تدمر النفس؟', en: 'Why Forbidden Relationships Destroy the Self' },
    show: { ar: 'بودكاست وعي', en: 'Waey Podcast' },
    host: { ar: 'مضيف وعي', en: 'Waey Host' },
    category: 'religion',
    duration: '48:30',
    views: '1.1M+',
    youtubeId: 'ryjSr_f7peg',
    description: { ar: 'نظرة شرعية ونفسية لأضرار العلاقات المحرمة.', en: 'Religious and psychological view on the harm of forbidden relationships.' },
    date: '2024'
  },
  {
    id: 61,
    title: { ar: 'الخلوة والدردشة المحرمة', en: 'Private Chat and Forbidden Seclusion' },
    show: { ar: 'د. لينة الحمصي', en: 'Dr. Lina Al-Homsi' },
    host: { ar: 'د. لينة الحمصي', en: 'Dr. Lina Al-Homsi' },
    category: 'religion',
    duration: '12:00',
    views: '320K',
    youtubeId: 'PXkfuzTCujs',
    description: { ar: 'لماذا الدردشة الخاصة بين الجنسين تُعد مدخلاً للعلاقات المحرمة؟', en: 'Why private chats between genders open the door to forbidden relationships.' },
    date: '2025'
  },
  {
    id: 62,
    title: { ar: 'كيف تبني علاقة صحية بعد تجربة مؤلمة؟', en: 'How to Build a Healthy Relationship After Pain' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'selfdev',
    duration: '2:40:00',
    views: '3.8M+',
    youtubeId: 'pJ0auP7dbcY',
    description: { ar: 'الشفاء من العلاقات السابقة وبناء أسس صحية جديدة.', en: 'Healing from past relationships and building healthy foundations.' },
    date: '2023'
  },
  {
    id: 63,
    title: { ar: 'الغيرة والتعلق المرضي في العلاقات', en: 'Jealousy and Toxic Attachment' },
    show: { ar: 'بودكاست بريدي', en: 'Baridi Podcast' },
    host: { ar: 'مضيف بريدي', en: 'Baridi Host' },
    category: 'psychology',
    duration: '55:00',
    views: '670K',
    youtubeId: '7bOjLi-1eAE',
    description: { ar: 'فهم الغيرة المفرطة والتعلق غير الصحي وكيفية التعامل معها.', en: 'Understanding excessive jealousy and unhealthy attachment.' },
    date: '2023'
  },
  {
    id: 64,
    title: { ar: 'هل الحب يكفي لاستمرار العلاقة؟', en: 'Is Love Enough to Sustain a Relationship?' },
    show: { ar: 'بودكاست فنجان', en: 'Fnjan Podcast' },
    host: { ar: 'عبدالرحمن أبومالح', en: 'Abdulrahman Abumalih' },
    category: 'selfdev',
    duration: '2:10:00',
    views: '5.1M+',
    youtubeId: 'pJ0auP7dbcY',
    description: { ar: 'أركان العلاقة الناجحة أبعد من مشاعر الحب فقط.', en: 'Pillars of a successful relationship beyond just feelings of love.' },
    date: '2022'
  },
  {
    id: 65,
    title: { ar: 'الرجل الساذج في الرايخ الثالث | الدحيح', en: 'The Naive Man in the Third Reich | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'history',
    duration: '33:21',
    views: '5.1M+',
    youtubeId: 'vUaLZYAiolw',
    description: { ar: 'قصة مثيرة عن الحياة في ألمانيا النازية.', en: 'A striking story about life in Nazi Germany.' },
    date: '2020'
  },
  {
    id: 66,
    title: { ar: 'أعظم تجربة في الفيزياء | الدحيح', en: 'The Greatest Experiment in Physics | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '23:37',
    views: '6.9M+',
    youtubeId: 'gPJhjnnBNAs',
    description: { ar: 'تجارب فيزيائية غيرت فهمنا للكون.', en: 'Physics experiments that changed our understanding of the universe.' },
    date: '2018'
  },
  {
    id: 67,
    title: { ar: 'أين ذهبت النساء؟ | الدحيح', en: 'Where Did the Women Go? | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'culture',
    duration: '19:35',
    views: '6.4M+',
    youtubeId: 'x_fW3gRHp2M',
    description: { ar: 'نظرة تاريخية واجتماعية على أدوار النساء.', en: 'Historical and social look at women roles.' },
    date: '2018'
  },
  {
    id: 68,
    title: { ar: 'الترجمة | الدحيح', en: 'Translation | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'culture',
    duration: '21:53',
    views: '3.3M+',
    youtubeId: 'MYANNltgLbk',
    description: { ar: 'فن وصعوبة الترجمة بين اللغات والثقافات.', en: 'The art and difficulty of translation across languages and cultures.' },
    date: '2018'
  },
  {
    id: 69,
    title: { ar: 'سمكة القرش | الدحيح', en: 'The Shark | Al-Daheeh' },
    show: { ar: 'الدحيح', en: 'Al-Daheeh' },
    host: { ar: 'أحمد الغندور', en: 'Ahmed El-Ghandour' },
    category: 'science',
    duration: '20:33',
    views: '4.8M+',
    youtubeId: 'cOch7WzE86o',
    description: { ar: 'حقائق مذهلة عن أسماك القرش.', en: 'Amazing facts about sharks.' },
    date: '2018'
  },
  {
    id: 70,
    title: { ar: 'كيف تتعامل مع الخيانة العاطفية؟', en: 'How to Deal with Emotional Betrayal' },
    show: { ar: 'بودكاست خطوة', en: 'Khatwa Podcast' },
    host: { ar: 'مضيف خطوة', en: 'Khatwa Host' },
    category: 'psychology',
    duration: '1:12:00',
    views: '540K',
    youtubeId: 'ChPPnSA7qCM',
    description: { ar: 'آثار الخيانة العاطفية وطرق التعافي وبناء الثقة من جديد.', en: 'Effects of emotional betrayal and ways to heal and rebuild trust.' },
    date: '2023'
  }
];
